spring:
  application:
    name: backend
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  config:
    import: optional:file:.env[.properties]

  ai:
    azure:
      openai:
        api-key: ${AZURE_OPENAI_API_KEY}
        endpoint: ${AZURE_OPENAI_ENDPOINT}
        client:
          http:
            connect-timeout: 30s
            response-timeout: 300s
        chat:
          options:
            deployment-name: ${AZURE_OPENAI_DEPLOYMENT_NAME}

  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

storage:
  access-key-id: ${LIGHTSAIL_ACCESS_KEY_ID}
  secret-access-key: ${LIGHTSAIL_SECRET_ACCESS_KEY}
  bucket-name: ${LIGHTSAIL_BUCKET_NAME}
  region: ${LIGHTSAIL_BUCKET_REGION}
  cdn-domain: ${LIGHTSAIL_CDN_DOMAIN}
  endpoint: ${LIGHTSAIL_ENDPOINT_URL}

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
